name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

  # Allows triggering workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install

      - name: build and test
      - run: npm run ci
