name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install dependencies
        run: npm ci

      - name: build and test
        run: npm run ci

      - name: publish release
        run: npm publish
